import 'styled-components';

declare module 'styled-components' {
  export interface DefaultTheme {
    typography: {
      family: {
        sansSerif: string,
        serif: string,
      },
      fontSize: number[],
      fontWeight: {
        300: number,
        400: number,
        500: number,
        700: number,
      },
    },
    iconography: {
      size: number[],
    },
    spacing: number[],
    layout: number[],
    borderRadius: {
      square : string,
      small: string,
      medium: string,
      large: string,
      pill: string,
      circle: string,
    },
    colors: {
      primary: {
        b100: string,
        b200: string,
        b300: string,
        b400: string,
        b500: string,
        b600: string,
        b700: string,
        b800: string,
        b900: string,
      },
      neutral: {
        charcoal: {
          c200: string,
          c300: string,
          c400: string,
          c500: string,
          c600: string,
          c700: string,
          c800: string,
        },
        ash: {
          a200: string,
          a300: string,
          a400: string,
          a500: string,
          a600: string,
          a700: string,
          a800: string,
        },
      },
      supporting: {
        teal: {
          t000: string,
          t100: string,
          t200: string,
          t300: string,
          t400: string,
          t500: string,
          t600: string,
          t700: string,
          t800: string,
          t900: string,
        },
        red: {
          r000: string,
          r100: string,
          r200: string,
          r300: string,
          r400: string,
          r500: string,
          r600: string,
          r700: string,
          r800: string,
          r900: string,
        },
        yellow: {
          y000: string,
          y100: string,
          y200: string,
          y300: string,
          y400: string,
          y500: string,
          y600: string,
          y700: string,
          y800: string,
          y900: string,
        },
      },
    },
    utilities: {
      boxShadow: {
        none: string,
        tiny: string,
        medium: string,
        large: string,
        huge: string,
      },
      zIndex: {
        z0: number,
        z1: number,
        z2: number,
        z3: number,
        z4: number,
        z5: number,
        z6: number,
        z7: number,
        z8: number,
        z9: number,
        z10: number,
      },
    },
  }
}
